@api = http://localhost:3000
GET {{api}}/heroes

###

POST {{ api }}/heroes
Content-Type: application/json

{
    "superhero"     :   "Fernando",
    "publisher"     :   "Dc Comics"
}

###
GET {{ api }}/usuarios/1
Content-Type: application/json